Hw03 mongodb
Mira1702/nodejs-homework-rest-api pull request #2
Opened 2021-05-16 16:49 UTC by Mira1702

2021-05-17 20:18 UTC, SergeiKBB requested changes

2021-05-17 20:18 UTC, SergeiKBB commented on .env
> +URI_DB = mongodb+srv://GoIT24:abdulaeva1702@cluster0.4twjr.mongodb.net/db-contacts?retryWrites=true&w=majority
этот файл должен быть добавлен в гитигноре

2021-05-18 17:00 UTC, Mira1702 commented on .env
> +URI_DB = mongodb+srv://GoIT24:abdulaeva1702@cluster0.4twjr.mongodb.net/db-contacts?retryWrites=true&w=majority
Исправила замечание

2021-05-19 20:42 UTC, SergeiKBB commented on .env
> +URI_DB = mongodb+srv://GoIT24:abdulaeva1702@cluster0.4twjr.mongodb.net/db-contacts?retryWrites=true&w=majority
файл все ещё сдесь. Его нужно удалить с ремоут репозитория

2021-05-20 19:37 UTC, Mira1702 commented on .env
> +URI_DB = mongodb+srv://GoIT24:abdulaeva1702@cluster0.4twjr.mongodb.net/db-contacts?retryWrites=true&w=majority
Исправила замечание, проверьте, пожалуйста

2021-05-21 12:15 UTC, SergeiKBB approved these changes

2021-05-22 09:02 UTC, merged